name: PrisonCore
version: 0.0.1
author: Pjinky
main: com.pjinky.prisoncore.Main
api-version: 1.13
commands:
  shop:
    usage: /shop
  dusør:
    usage: /dusør
  plsopmig:
    usage: /plsopmig
  gethead:
    usage: /gethead
  bande:
    usage: /bande