name: PrisonCore
version: 0.0.1
author: Pjinky
main: com.pjinky.prisoncore.Main
api-version: 1.13
commands:
  shop:
    description: Add description yeah
    usage: /shop
  dusør:
    description: hi
    usage: /dusør
  plsopmig:
    description:
    usage: Find selv ud af det
  gethead:
    description:
    usage: ok